/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sachin
 */
public class LeaveTaker extends javax.swing.JFrame {

    /**
     * Creates new form LeaveTaker
     */
    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public LeaveTaker() throws ClassNotFoundException {
        initComponents();

        conn = dbConn.getConn();

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();

        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comb_leaveType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        date_from_chooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        Date_To_Chooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txt_NoOfDays = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_id_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_test = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Leave Taker");

        jLabel2.setText("Leave Type");

        comb_leaveType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily Leave", "Monthly Leave " }));
        comb_leaveType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_leaveTypeActionPerformed(evt);
            }
        });

        jLabel3.setText("Date from");

        jLabel4.setText("Date To");

        Date_To_Chooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Date_To_ChooserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Date_To_ChooserKeyReleased(evt);
            }
        });

        jLabel5.setText("No Of Days");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/images/Clear-icon.png"))); // NOI18N
        jButton1.setText("Clear");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/images/Exit.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/images/Calculate.png"))); // NOI18N
        jButton3.setText("Approve Leave");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        btn_test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/images/Right3Green.png"))); // NOI18N
        btn_test.setText("Check");
        btn_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_testActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 236, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(94, 94, 94)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(222, 222, 222)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(txt_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(90, 90, 90)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(comb_leaveType, 0, 212, Short.MAX_VALUE)
                                                .addComponent(date_from_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Date_To_Chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                            .addComponent(txt_NoOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(39, 39, 39)
                                    .addComponent(btn_test, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(173, 173, 173)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(653, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGap(40, 40, 40)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comb_leaveType, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48, 48, 48)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(date_from_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(45, 45, 45)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Date_To_Chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(62, 62, 62)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_NoOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btn_test, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(99, 99, 99)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(87, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(301, 301, 301)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(61, 61, 61)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int x = JOptionPane.showConfirmDialog(null, "sure To Add Record?", "Confirm Adding New Record", JOptionPane.YES_NO_OPTION);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date_from = sdf.format(date_from_chooser.getDate());
        String date_to = sdf.format(Date_To_Chooser.getDate());

        if (x == JOptionPane.YES_OPTION) {
//            try {
//                String sql = "SELECT DATEDIFF(day, '" + date_from + "', '" + date_to + "') AS DateDiff;";
//
//                pst = conn.prepareStatement(sql);
//
//                rs = pst.executeQuery();
//                while (rs.next()) {
//                    loggedinId.workDays = rs.getString("DateDiff");
//                }
//
//                txt_NoOfDays.setText(loggedinId.workDays);
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(null, ex);
//            }
            try {
                String sql = "INSERT INTO leave_taker(emp_id,startDate,endDate,noDays) VALUES (?,?,?,?)";

                pst = conn.prepareStatement(sql);

                pst.setString(1, txt_id_field.getText());

//                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//                String date_from = sdf.format(date_from_chooser.getDate());
                pst.setString(2, date_from);

//                String date_to = sdf.format(Date_To_Chooser.getDate());
                pst.setString(3, date_to);
                pst.setString(4, txt_NoOfDays.getText());

                pst.execute();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            } finally {
                try {
                    //  rs.close();
                    pst.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Record Not Added", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comb_leaveTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_leaveTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_leaveTypeActionPerformed

    private void Date_To_ChooserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Date_To_ChooserKeyReleased
        // TODO add your handling code here:
//
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//        String date_from = sdf.format(date_from_chooser.getDate());
//        String date_to = sdf.format(Date_To_Chooser.getDate());
//
//        try {
//            String sql = "SELECT DATEDIFF(day, '" + date_from + "', '" + date_to + "') AS DateDiff;";
//
//            pst = conn.prepareStatement(sql);
//
//            rs = pst.executeQuery();
//            while (rs.next()) {
//                loggedinId.workDays = rs.getString("DateDiff");
//            }
//
//            txt_NoOfDays.setText(loggedinId.workDays);
//            System.out.println(loggedinId.workDays);
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex);
//        } finally {
//            try {
//                //  rs.close();
//                pst.close();
//            } catch (SQLException e) {
//                JOptionPane.showMessageDialog(null, e);
//            }
//        }

    }//GEN-LAST:event_Date_To_ChooserKeyReleased

    private void Date_To_ChooserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Date_To_ChooserKeyPressed
//
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//        String date_from = sdf.format(date_from_chooser.getDate());
//        String date_to = sdf.format(Date_To_Chooser.getDate());
//
//        try {
//            String sql = "SELECT DATEDIFF(day, '" + date_from + "', '" + date_to + "') AS DateDiff;";
//
//            pst = conn.prepareStatement(sql);
//
//            rs = pst.executeQuery();
//            while (rs.next()) {
//                loggedinId.workDays = rs.getString("DateDiff");
//            }
//
//            txt_NoOfDays.setText(loggedinId.workDays);
//            System.out.println(loggedinId.workDays);
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex);
//        } finally {
//            try {
//                //  rs.close();
//                pst.close();
//            } catch (SQLException e) {
//                JOptionPane.showMessageDialog(null, e);
//            }
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Date_To_ChooserKeyPressed

    private void btn_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_testActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date_from = sdf.format(date_from_chooser.getDate());
        String date_to = sdf.format(Date_To_Chooser.getDate());
        String noTime = "00:00:00";

        try {
            String sql = "SELECT DATEDIFF('" + date_to + " " + noTime + "', '" + date_from +" "+noTime+ "') AS DateDiff;";

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            while (rs.next()) {
                loggedinId.workDays = rs.getString("DateDiff");
            }

            txt_NoOfDays.setText(loggedinId.workDays);
            System.out.println(loggedinId.workDays);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                //  rs.close();
                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_btn_testActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveTaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LeaveTaker().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LeaveTaker.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_To_Chooser;
    private javax.swing.JButton btn_test;
    private javax.swing.JComboBox<String> comb_leaveType;
    private com.toedter.calendar.JDateChooser date_from_chooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_NoOfDays;
    private javax.swing.JTextField txt_id_field;
    // End of variables declaration//GEN-END:variables
}
